TradingCompanyMVC/Controllers/ItemController.cs
using AutoMapper;
using BusinessLogic.Concrete;
using BusinessLogic.Interfaces;
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TradingCompanyMVC.App.Security;
using TradingCompanyMVC.Models;

namespace TradingCompanyMVC.Controllers
{
    public class ItemController : Controller
    {
        protected readonly IItemManager _manager;
        protected readonly ICategoryManager _categoryManager;
        protected readonly IMapper _mapper;

        public ItemController(IMapper mapper, IItemManager manager,ICategoryManager categoryManager)
        {
            _mapper = mapper;
            _manager = manager;
            _categoryManager = categoryManager;
        }
        // GET: Item
        public ActionResult Index()
        {

            List<ItemDTO> all_items =_manager.GetAllItems();

            var converted = new List<ItemModel>();
            foreach (var p in all_items)
            {
                converted.Add(_mapper.Map<ItemModel>(p));
            }
            return View(converted);
        }

        // GET: Item/Details/5
        public ActionResult Details(int id)
        {
            var item = this._manager.GetItemById(id);
            return View(item);
        }

        // GET: Item/Create
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var create_item = new EditItemModel();
            create_item.Categories = new List<SelectListItem>();
            foreach (var cat in _categoryManager.GetAllCategories())
            {
                create_item.Categories.Add(_mapper.Map<SelectListItem>(cat));
            }
            return View(create_item);
        }

        // POST: Item/Create
        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Create(EditItemModel collection)
        {
            try
            {
                // TODO: Add insert logic here
                this._manager.AddItem(_mapper.Map<ItemDTO>(collection));
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Item/Edit/5
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var item = this._manager.GetItemById(id);
            var edit_item = _mapper.Map<EditItemModel>(item);
            edit_item.Categories = new List<SelectListItem>();
            foreach(var cat in _categoryManager.GetAllCategories())
            {
                edit_item.Categories.Add(_mapper.Map<SelectListItem>(cat));
            }
            return View("~/Views/Item/EditItemView.cshtml",edit_item);
        }

        // POST: Item/Edit/5
        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Edit(int id, ItemDTO collection)
        {
            try
            {
                // TODO: Add update logic here
                this._manager.UpdateItem(collection);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Item/Delete/5
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var item = this._manager.GetItemById(id);
            return View(item);
        }

        // POST: Item/Delete/5
        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                this._manager.DeleteItemById(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TradingCompanyMVC/Controllers/OrderController.cs
using AutoMapper;
using BusinessLogic.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TradingCompanyMVC.App.Security;
using TradingCompanyMVC.Models;

namespace TradingCompanyMVC.Controllers
{
    public class OrderController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IOrderManager _orderManager;
        private readonly IItemManager _itemManager;
        private readonly IOrderStatusManager _orderStatusManager;
        private readonly IOrderedManager _orderedManager;
        public OrderController(IMapper mapper,
            IOrderManager orderManager,
            IItemManager itemManager,
            IOrderStatusManager orderStatusManager,
            IOrderedManager orderedManager)
        {
            _mapper = mapper;
            _orderManager = orderManager;
            _itemManager = itemManager;
            _orderManager = orderManager;
            _orderedManager = orderedManager;
            _orderStatusManager = orderStatusManager;

        }
        // GET: Order
        [CustomAuthorize(Roles ="User")]
        public ActionResult Index()
        {   
            var user = HttpContext.User as CustomPrincipal;
            var orders = _orderManager.GetAllOrdersByUserId(user.UserID);

           
            return View(orders);
        }

        // GET: Order/Details/5
        [CustomAuthorize(Roles = "User")]
        public ActionResult Details(int id)
        {

            FullOrderInfo order = _mapper.Map<FullOrderInfo>(this._orderManager.GetOrderById(id));
            order.OrderedProducts = new List<OrderedInfo>();

            order.StatusName = this._orderStatusManager.GetOrderStatusById(order.StatusID).Name;

            var all_ordered = _orderedManager.GetOrderedListById(order.OrderID);

            OrderedInfo temp;
            foreach (var o in all_ordered)
            {
                temp = _mapper.Map<OrderedInfo>(o);
                
                temp.ItemTitle = _itemManager.GetItemById(temp.ItemID).ItemTitle;
                order.OrderedProducts.Add(temp);
            }


            return View(order);
        }
       
    }
}

TradingCompanyMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Items", "Index", "Item")</li>
                    @if (User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("My orders", "Index", "Order")</li>
                    }

                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Logout", "LogOut", "Account")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>